title: "Mageplaza"
url: "https://www.mageplaza.com"
description: "Mageplaza is a leading provider of Magento 2 extensions and services. We help businesses grow and succeed online with our innovative solutions."

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - _site
  - package*.json
  - "*.config.js"
  - README.md
  - node_modules
  - core
  - Gemfile
  - Gemfile.lock

collections:
  team:
    output: true
  values:
    output: false

include:
  - _pages

permalink: pretty
